POST http://localhost:9090/register
Content-Type: application/json

{
  "username": "harish123",
  "password": "mypassword",
  "email": "harish@example.com",
  "name": "Harish"
}

###
POST http://localhost:9090/login
Content-Type: application/json

{
  "email": "harish@example.com",
  "password": "mypassword"
}
