POST http://localhost:9090/register
Content-Type: application/json

{
  "username": "harish123",
  "password": "mypassword",
  "email": "harish@example.com",
  "name": "Harish"
}

###
POST http://localhost:9090/login
Content-Type: application/json

{
  "email": "harish@example.com",
  "password": "mypassword"
}

###
GET http://localhost:9090/get_user_and_profile
Content-Type: application/json

{
  "token": "6fab78e361318a2c594c83c630a1ede15a1ac1b50977aaac8bc5ae7f5e11bd1b"
}